### ISSUE TITLE
bug with MenuItem.js   tag:v2.6.0 and npm package

### ISSUE THREAD

**Issue by Crayonn** [vkbansal/react-contextmenu#116]
if onMouseLeave and onMouseMove is not default value,There is warning.

**Comment by vkbansal** [comment]
Can you elaborate a bit more? In which component are you seeing this?

**Comment by codeart1st** [comment]
Fixed with 9a0eb8926d1cc7515b648f1308f83c2a4cba9d8d

**Comment by Crayonn** [comment]
@codeart1st 
but npm package still have this problem

MenuItem.js in npm package  

`export default class MenuItem extends Component {
    static propTypes = {
        children: PropTypes.node,
        attributes: PropTypes.object,
        data: PropTypes.object,
        disabled: PropTypes.bool,
        divider: PropTypes.bool,
        preventClose: PropTypes.bool,
        onClick: PropTypes.func,
        selected: PropTypes.bool,
        onMouseMove: PropTypes.func.isRequired,
        onMouseLeave: PropTypes.func.isRequired
    };

    static defaultProps = {
        disabled: false,
        data: {},
        divider: false,
        attributes: {},
        preventClose: false,
        onClick() { return null; },
        children: null,
        selected: false
    };`

should be 

`static defaultProps = {
        disabled: false,
        data: {},
        divider: false,
        attributes: {},
        preventClose: false,
        onClick() { return null; },
        children: null,
        selected: false
        onMouseMove: () => null,
        onMouseLeave: () => null,
    };`

**Comment by vkbansal** [comment]
Just publish v2.6.1 with the fix. Sorry for the delay in publishing.

**Comment by Crayonn** [comment]
@vkbansal 
thank you! 
Very honored to your reply!
