### ISSUE TITLE
keyboard event listener not unregistered

### ISSUE THREAD

**Issue by loicbourg** [vkbansal/react-contextmenu#176]
## Version
1.9.1

## Test Case
https://jsfiddle.net/6ty1r8yn/1/

## Steps to reproduce
- Right click on the context menu trigger.
- Hover the first Sub menu
- Click "Ajouter"
- Type some text in the textarea and try to add a new line with enter

## Expected Behavior
I should have a text with multiple new line in the textarea

## Actual Behavior
no new line is added

## Additional informations
The arrow key are also not working.

I suspect it comes from https://github.com/vkbansal/react-contextmenu/blob/master/src/AbstractMenu.js#L21

in the console there is a warning when using the arrow key or enter:
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the t component.

**Comment by loicbourg** [comment]
Any idea about the origin of the bug ?

**Comment by vkbansal** [comment]
I've published react-contextmenu@2.9.2-alpha.1 with possible fix. Can you try it?

**Comment by loicbourg** [comment]
@vkbansal thanks for the release !
That's working better now but there is still a problem on the first press on the Enter key, but the next press are working.

example here: https://jsfiddle.net/6ty1r8yn/1/

**Comment by vkbansal** [comment]
This issue is caused by https://github.com/vkbansal/react-contextmenu/blob/master/src/SubMenu.js#L215

This will need a deep dive and may take some time
